import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/shared/provider";
import { Header } from "@/components/shared/header";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BookOn – Интернет магазин книг",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Provider>
          <Header />
          <main className="mb-[200px]">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
